Generate docs when using library mode
eigerco/uniffi-rs pull request #10
Opened 2023-10-10 17:06 UTC by skeet70

Adds a call to generate docs when using library mode (as recommended by the docs for proc macros). This worked in our medium sized project that uses only proc-macros+library mode.

2023-10-26 11:19 UTC, MeerKatDev commented
Hi, could you solve the conflicts? I'm sorry if I messed up with them myself. Let me know if I can somehow help.

2023-10-26 18:31 UTC, skeet70 commented
> Hi, could you solve the conflicts? I'm sorry if I messed up with them myself. Let me know if I can somehow help.

I merged main in. It's still working for our project and the tests I can run still pass.

2023-10-26 18:56 UTC, MeerKatDev requested changes

2023-10-26 18:56 UTC, MeerKatDev commented on uniffi_bindgen/src/library_mode.rs
> +    for source in sources.iter_mut() {
Also, in the last version of the code, this part was extracted

2023-10-26 18:56 UTC, MeerKatDev commented on uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift
> +    {% include "EnumVariantDocsTemplate.swift" %}
thank you!

2023-10-26 19:25 UTC, MeerKatDev commented on uniffi_bindgen/src/library_mode.rs
> +    for source in sources.iter_mut() {
I mean - is it possible to reuse the code here?

2023-10-27 22:38 UTC, skeet70 commented on uniffi_bindgen/src/library_mode.rs
> +    for source in sources.iter_mut() {
Very possible, I've just been blazing forward with using this, trying to release and document the product we're building with it. I have another hackday in two weeks, but I can try to come back and take a look at consolidating in between tickets before then.

2023-11-01 17:20 UTC, skeet70 commented on uniffi_bindgen/src/library_mode.rs
> +    for source in sources.iter_mut() {
I think I've done this, and removed the methods I had added to do it. If you were thinking of a different reusable part let me know.

2023-11-27 23:16 UTC, closed without merging